### ISSUE TITLE
I don't have IOS or Windows

### ISSUE THREAD

**Issue by ghost** [MaxvandeLaar/homey-community-store#13]
Unfortunately I don't have an IOS or Windows. My computers all run on Linux Mint which is based on Ubuntu.
It would be great if there was something for that too.

**Comment by MaxvandeLaar** [comment]
@copiis Version 0.2.0 has a build for Linux OS as well, I did not have the chance yet to try them... https://github.com/MaxvandeLaar/homey-community-store/releases/tag/v0.2.0 If you could test these that would be great.

**Comment by ghost** [comment]
This message comes directly at the start.
![Bildschirmfoto vom 2020-05-18 09-34-53](https://user-images.githubusercontent.com/12480023/82186257-d9ad3d80-98ea-11ea-9bcc-18047584f75d.png)

**Comment by MaxvandeLaar** [comment]
Hmm so is the apparently the store isn't allowed to create/write to that folder. I will look into that later tonight. The store needs to create some additional folders etc... so if it can't do that, it will cause issues. I suppose this I need to use a different folder when OS is Linux based.

Thanks for the test :)

**Comment by MaxvandeLaar** [comment]
@copiis could you try the v0.3.0 beta? 

It's an AppImage so just make it executable https://discourse.appimage.org/t/how-to-run-an-appimage/80

**Comment by MaxvandeLaar** [comment]
No need for installers anymore as I just released the web version [here](https://store.homey.community)
