### ISSUE TITLE
Windows 10 no go

### ISSUE THREAD

**Issue by Sen-Sai** [MaxvandeLaar/homey-community-store#16]
Running the latest version from your website (version file tells me v8.2.0) on the latest Windows 10 (all updates are installed) simply nothing happens. Running as Administrator just gives me a pop-up to ask if I'm sure to run it as admin.. then nothing happens. Also no services or processes in the task manager.

**Comment by MaxvandeLaar** [comment]
@Sen-Sai sorry missed this issue. Could you try with the v0.3.0 beta? This new version is build with a different build-tool and it now became a windows installer instead of an unpackaged app.

**Comment by Sen-Sai** [comment]
Thanks! That seems to work! Although it would be nice if I could set the installation path.. nevertheless. Thanks!
