### ISSUE TITLE
Translation of App Descriptions / App Store itself

### ISSUE THREAD

**Issue by carp3-noctem** [MaxvandeLaar/homey-community-store#19]
**Is your feature request related to a problem? Please describe.**
Ability to switch between Languages. And also display corresponding Translations from Apps.

**Describe the solution you'd like**
Make use of a Webservice (crowdin is free for open source projects), to be able to translate the Appstore and maybe the App describtions.

**Describe alternatives you've considered**
Language Selector for Appstore, but if language is not supported from Apps Source, fall back to English

**Additional context**
Crowdin can be easily setup to create on the Fly Translations for Wordstrings. It may Help to get all Languages. It may be setup to create Pull requests for other Projects after a translation is done in the AppStore.

**Comment by MaxvandeLaar** [comment]
The App Store will use the same locale as the OS and also uses the translations provided by the app developers for their apps. If these are not present, or a locale is not supported by the Store or an app, locale will fallback to English
