### ISSUE TITLE
impossible to login

### ISSUE THREAD

**Issue by mcrbrauers** [MaxvandeLaar/homey-community-store#29]
It's not possible to login because an of an error.
I fill in my Athom Homey username and password, then click OK.
Then I accept the popup HOMEY CLI OLD.
Then the Athom Homey logo is beeing displayed on the screen........ and nothing will happen.

It seems that it's impossible to login to homey. 
Maybe the app or the connecion has an error. 

Is it possible to fix this issue?

**Comment by reulnl** [comment]
Just upgraded my good old Homey to a new Homey Pro 2023. After migration I'm missing quite some apps, as they're from the Homey Community Store.

However, I'm also unable to login to the Homey Community Store. I keep getting the following error message after logging in:

```
Could not automatically log you in.
Please copy & paste the code below in the command-line.
```

When I add the authorization code in the browser I get the following error:
`Client credentials are invalid
`

The Homey Community Store app on both OSX and Windows doesn't show an option to paste the authorization code.

**Comment by trivarialthea** [comment]
@MaxvandeLaar any updates on this?, i am also having this issue, excluding that i only have 1 homey... And there is no way to enter the cli code generated by the website.

**Comment by Alesschen** [comment]
Same issue here, unable to login (credentials are invalid)

**Comment by pjmpessers** [comment]
Same problem. Will there be a fix soon? :-)

**Comment by swap83** [comment]
I have the same problem

**Comment by fabdemar63** [comment]
I have the same problem.. news?

**Comment by Alesschen** [comment]
Can you provide some feedback on whether or not this will be resolved?

**Comment by MaxvandeLaar** [comment]
I am going to close this as the HCS is offline. https://community.homey.app/t/homey-community-app-store/29865/292?u=maxvandelaar
