### ISSUE TITLE
Unable to register my device

### ISSUE THREAD

**Issue by pippo73** [MaxvandeLaar/homey-community-store#30]
**Describe the bug**
I'm trying to connect my homey pro device to your platform, but I get stuck to the https://cli.athom.com/ page

**To Reproduce**
1. Go the webpage https://store.homey.community/login
2. Click on "Sign in at Athom" button
3. Select the accont/login in the account you want to use
4. Allow "Homey CLI Old would like to..." to all the flag by pressing the button allow
5. since it does not connect automatically copy the code
6. enter the string in the field of the first page and press "send"

**Expected behavior**
The device is registered

**Screenshots**

![3](https://github.com/MaxvandeLaar/homey-community-store/assets/757121/70f10382-9eaa-4991-96df-0f5e1eaf9f8e)

**Desktop (please complete the following information):**
 - OS: windows11
 - App Store version: don't know where to see it :-(
 - Browser : firefox 115

**Additional context**

**Comment by MaxvandeLaar** [comment]
Replica of https://github.com/MaxvandeLaar/homey-community-store/issues/29 

HCS is no longer available.
