### ISSUE TITLE
Error during app install

### ISSUE THREAD

**Issue by AdyRock** [MaxvandeLaar/homey-community-store#4]
I am using the Windows version of the store app.
I tried to install an update to the Neo coolcam app but it never appears in Homey. In the console of the Store app I got the following:
[1589221153596.log](https://github.com/MaxvandeLaar/homey-community-store/files/4611392/1589221153596.log)

renderer.tsx:80 Profile Object
renderer.tsx:80 Profile Object
Content.tsx:69 Progress NEO Coolcam {step: 1, totalSteps: 4, message: "Start downloading NEO Coolcam"}step: 1totalSteps: 4message: "Start downloading NEO Coolcam"__proto__: Object
Content.tsx:69 Progress NEO Coolcam {step: 1, totalSteps: 4, message: "Start downloading NEO Coolcam"}
Content.tsx:69 Progress NEO Coolcam {step: 1, totalSteps: 4, message: "Start downloading NEO Coolcam"}
Content.tsx:69 Progress NEO Coolcam {step: 1, totalSteps: 4, message: "Completed downloading NEO Coolcam"}
Content.tsx:69 Progress NEO Coolcam {step: 1, totalSteps: 4, message: "Completed downloading NEO Coolcam"}
Content.tsx:69 Progress NEO Coolcam {step: 1, totalSteps: 4, message: "Completed downloading NEO Coolcam"}
Content.tsx:69 Progress NEO Coolcam {step: 2, totalSteps: 4, message: "Start extracting NEO Coolcam"}
Content.tsx:69 Progress NEO Coolcam {step: 2, totalSteps: 4, message: "Start extracting NEO Coolcam"}
Content.tsx:69 Progress NEO Coolcam {step: 2, totalSteps: 4, message: "Start extracting NEO Coolcam"}
Content.tsx:69 Progress NEO Coolcam {step: 2, totalSteps: 4, message: "Finished extracting NEO Coolcam"}
Content.tsx:69 Progress NEO Coolcam {step: 2, totalSteps: 4, message: "Finished extracting NEO Coolcam"}
Content.tsx:69 Progress NEO Coolcam {step: 2, totalSteps: 4, message: "Finished extracting NEO Coolcam"}
Content.tsx:69 Progress NEO Coolcam {step: 3, totalSteps: 4, message: "Start installation preparations NEO Coolcam"}
Content.tsx:69 Progress NEO Coolcam {step: 3, totalSteps: 4, message: "Start installation preparations NEO Coolcam"}
Content.tsx:69 Progress NEO Coolcam {step: 3, totalSteps: 4, message: "Start installation preparations NEO Coolcam"}
Content.tsx:69 Progress NEO Coolcam {step: 3, totalSteps: 4, message: "Finished installation preparations NEO Coolcam"}
Content.tsx:69 Progress NEO Coolcam {step: 3, totalSteps: 4, message: "Finished installation preparations NEO Coolcam"}
Content.tsx:69 Progress NEO Coolcam {step: 3, totalSteps: 4, message: "Finished installation preparations NEO Coolcam"}
Content.tsx:69 Progress NEO Coolcam {step: 4, totalSteps: 4, message: "Start installation NEO Coolcam"}
Content.tsx:69 Progress NEO Coolcam {step: 4, totalSteps: 4, message: "Start installation NEO Coolcam"}
Content.tsx:69 Progress NEO Coolcam {step: 4, totalSteps: 4, message: "Start installation NEO Coolcam"}
VM110:1 Uncaught SyntaxError: Unexpected token o in JSON at position 1
    at JSON.parse (<anonymous>)
    at EventEmitter.<anonymous> (Content.tsx:168)
    at EventEmitter.emit (events.js:210)
    at Object.onMessage (init.ts:50)
(anonymous) @ Content.tsx:168
emit @ events.js:210
onMessage @ init.ts:50

**Comment by MaxvandeLaar** [comment]
@AdyRock, can you please check with v0.1.4?
