### ISSUE TITLE
Login to Athom on mac

### ISSUE THREAD

**Issue by jaxc0402** [MaxvandeLaar/homey-community-store#5]
I cannot login to Athom in the store on my Mac (button does nothing)

**Comment by MaxvandeLaar** [comment]
@jaxc0402, did you get a popup looking something like this? 
![image](https://user-images.githubusercontent.com/5842932/81660951-b8a4a280-943b-11ea-9ae9-b41b2ca007c7.png)

When clicking this button the app calls initialises the official homey api which checks if you are signed in to the cli. If not you get redirected to the homey login page in your default webbrowser to login. This should be enough, however, I just checked again and I had to click the signing button  a second time and select my account in my webbrowser to use. Could you try that? I do realise I should look into that.

**Comment by MaxvandeLaar** [comment]
This got fixed in a version update to v0.1.3
