### ISSUE TITLE
App request: Smart presence latest update

### ISSUE THREAD

**Issue by matrover** [MaxvandeLaar/homey-community-store#6]
- Repo: https://bitbucket.org/terryhendrix/homey-smartpresence/
 - Stable branch: https://bitbucket.org/terryhendrix/homey-smartpresence/src/master/

Difference from the Official app store is that the user tile wil represent the user at home status (kinda like on/off) which has been an much requested feature, but for official admission the app needs to be rewritten, in the thought that this take a lot of time and the app works perfectly this is not high on the developers list.

**Comment by MaxvandeLaar** [comment]
@matrover will add this soon. Current app version does not yet support BitBucket. Made some changes to get this to work, however, I want to add one more feature before releasing v0.2.0
