### ISSUE TITLE
App description update request

### ISSUE THREAD

**Issue by matrover** [MaxvandeLaar/homey-community-store#7]
is it possible to include this description to the D&M app? 

https://community.athom.com/t/app-denon-heos-app-form-nlrb-not-in-app-store/

it has been made in coop. with the developer, and is much richer

**Comment by MaxvandeLaar** [comment]
@matrover Sadly, this cannot be achieved that this moment. Descriptions are loaded directly from the app.json and readme file inside the repo. Changes should be applied there. 

However, in the future I plan to show more information from the app.json file such as collaborators, languages etc...
